name: android-build

on: [push, pull_request]

jobs:
  build-apk-for-android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cloning modlaucher repo and preparing for building
      run: |
        git clone https://github.com/ItzVladik/srceng-mod-launcher
        sudo apt-get update
        sudo apt-get install -f -y openjdk-8-jre zip apksigner imagemagick zlib1g libc6 libstdc++6 libopenal-dev g++-multilib gcc-multilib libpng-dev libjpeg-dev libfreetype6-dev libfontconfig1-dev libcurl4-gnutls-dev libsdl2-dev zlib1g-dev libbz2-dev libedit-dev
    - name: Build Android (32 bit)
      run: |
        scripts/build-android-armv7a.sh
    - name: Build Android (64 bit)
      run: |
        chmod +x scripts/build-android-aarch64.sh
        scripts/build-android-aarch64.sh   
    - name: Build APK
      run: |
        chmod +x scripts/build-apk.sh
        scripts/build-apk.sh
    - name: Rename APK
      run: |
         mv srceng-mod-launcher/build/android/mod-signed.apk mod-release.apk

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: mod-apk
        path: mod-release.apk
