name: android-build

on: [push, pull_request]

jobs:
  build-apk-for-android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cloning modlaucher repo and preparing for building
      run: |
        git clone https://github.com/ItzVladik/srceng-mod-launcher
        sudo apt-get update
        sudo apt-get install -f -y openjdk-8-jre zip apksigner imagemagick zlib1g:i386 libc6:i386 libncurses5:i386 libstdc++6:i386 libopenal-dev:i386 g++-multilib gcc-multilib libpng-dev:i386 libjpeg-dev:i386 libfreetype6-dev:i386 libfontconfig1-dev:i386 libcurl4-gnutls-dev:i386 libsdl2-dev:i386 zlib1g-dev:i386 libbz2-dev:i386 libedit-dev:i386
    - name: Build Android (32 bit)
      run: |
        scripts/build-android-armv7a.sh
    - name: Build Android (64 bit)
      run: |
        chmod +x scripts/build-android-aarch64.sh
        scripts/build-android-aarch64.sh   
    - name: Build APK
      run: |
        chmod +x scripts/build-apk.sh
        scripts/build-apk.sh
    - name: Rename APK
      run: |
         mv srceng-mod-launcher/build/android/mod-signed.apk mod-release.apk

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: mod-apk
        path: mod-release.apk
